name: Swift Build

on: [push]

jobs:
  build:
    runs-on: macOS-12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
    - name: Build
      run: swift build -v
